2020/04/28 16:48:23 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in /var/www/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Assignment_2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=gii/default/index
---
2020/04/28 16:50:37 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in /var/www/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Assignment_2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=gii/
---
2020/04/28 16:52:56 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in /var/www/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Assignment_2/index.php?r=gii/model/index
---
2020/04/28 17:24:17 [error] [exception.Error] Error: Class 'app\assets\AppAsset' not found in /var/www/html/Assignment_2/protected/views/layouts/main.php:14
Stack trace:
#0 /var/www/yii/framework/web/CBaseController.php(126): require()
#1 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/A...', Array, true)
#2 /var/www/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/html/A...', Array, true)
#3 /var/www/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#4 /var/www/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#5 /var/www/yii/framework/web/CBaseController.php(215): COutputProcessor->run()
#6 /var/www/yii/framework/web/CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#7 /var/www/html/Assignment_2/protected/views/layouts/column2.php(22): CBaseController->endContent()
#8 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/html/A...')
#9 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/A...', Array, true)
#10 /var/www/yii/framework/web/CController.php(787): CBaseController->renderFile('/var/www/html/A...', Array, true)
#11 /var/www/html/Assignment_2/protected/controllers/UsersController.php(127): CController->render('index', Array)
#12 /var/www/yii/framework/web/actions/CInlineAction.php(49): UsersController->actionIndex()
#13 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#14 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#15 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#16 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#17 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#18 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#19 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#20 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('')
#22 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#23 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#24 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/Assignment_2/index.php?r=users
---
2020/04/28 17:26:29 [error] [exception.Error] Error: Class 'app\assets\AppAsset' not found in /var/www/html/Assignment_2/protected/views/layouts/main.php:14
Stack trace:
#0 /var/www/yii/framework/web/CBaseController.php(126): require()
#1 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/A...', Array, true)
#2 /var/www/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/html/A...', Array, true)
#3 /var/www/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#4 /var/www/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#5 /var/www/yii/framework/web/CBaseController.php(215): COutputProcessor->run()
#6 /var/www/yii/framework/web/CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#7 /var/www/html/Assignment_2/protected/views/layouts/column2.php(22): CBaseController->endContent()
#8 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/html/A...')
#9 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/A...', Array, true)
#10 /var/www/yii/framework/web/CController.php(787): CBaseController->renderFile('/var/www/html/A...', Array, true)
#11 /var/www/html/Assignment_2/protected/controllers/UsersController.php(127): CController->render('index', Array)
#12 /var/www/yii/framework/web/actions/CInlineAction.php(49): UsersController->actionIndex()
#13 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#14 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#15 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#16 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#17 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#18 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#19 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#20 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('')
#22 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#23 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#24 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/Assignment_2/index.php?r=users
---
2020/04/28 18:08:35 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/views/users/index.php:16)
Stack trace:
#0 /var/www/yii/framework/web/CController.php(872): UsersController->renderFile()
#1 /var/www/yii/framework/web/CController.php(785): UsersController->renderPartial()
#2 /var/www/html/Assignment_2/protected/controllers/UsersController.php(119): UsersController->render()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(49): UsersController->actionIndex()
#4 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#6 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#8 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#9 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#10 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#12 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/views/users/index.php (16)
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (119)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:09:20 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/views/users/index.php:16)
Stack trace:
#0 /var/www/yii/framework/web/CController.php(872): UsersController->renderFile()
#1 /var/www/yii/framework/web/CController.php(785): UsersController->renderPartial()
#2 /var/www/html/Assignment_2/protected/controllers/UsersController.php(119): UsersController->render()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(49): UsersController->actionIndex()
#4 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#6 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#8 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#9 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#10 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#12 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/views/users/index.php (16)
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (119)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:11:24 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/views/users/index.php:14)
Stack trace:
#0 /var/www/yii/framework/web/CController.php(872): UsersController->renderFile()
#1 /var/www/yii/framework/web/CController.php(785): UsersController->renderPartial()
#2 /var/www/html/Assignment_2/protected/controllers/UsersController.php(119): UsersController->render()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(49): UsersController->actionIndex()
#4 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#6 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#8 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#9 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#10 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#12 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/views/users/index.php (14)
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (119)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:12:29 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/controllers/UsersController.php:122)
Stack trace:
#0 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#1 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#5 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (122)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:12:44 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/controllers/UsersController.php:122)
Stack trace:
#0 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#1 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#5 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (122)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:12:45 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/controllers/UsersController.php:122)
Stack trace:
#0 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#1 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#5 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (122)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:12:47 [error] [php] Undefined variable: model (/var/www/html/Assignment_2/protected/controllers/UsersController.php:122)
Stack trace:
#0 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#1 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#5 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (122)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:21:44 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/
---
2020/04/28 18:22:11 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/
---
2020/04/28 18:22:25 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/index
---
2020/04/28 18:32:34 [error] [php] Undefined variable: dataProvider (/var/www/html/Assignment_2/protected/views/users/index.php:19)
Stack trace:
#0 /var/www/yii/framework/web/CController.php(872): UsersController->renderFile()
#1 /var/www/yii/framework/web/CController.php(785): UsersController->renderPartial()
#2 /var/www/html/Assignment_2/protected/controllers/UsersController.php(124): UsersController->render()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(49): UsersController->actionIndex()
#4 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/filters/CFilterChain.php(134): UsersController->runAction()
#6 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(1148): CAccessControlFilter->filter()
#8 /var/www/yii/framework/web/filters/CInlineFilter.php(58): UsersController->filterAccessControl()
#9 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#10 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/yii/framework/web/CController.php(265): UsersController->runActionWithFilters()
#12 /var/www/yii/framework/web/CWebApplication.php(282): UsersController->run()
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#14 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/Assignment_2/index.php(13): CWebApplication->run()
REQUEST_URI=/Assignment_2/index.php?r=users/
in /var/www/html/Assignment_2/protected/views/users/index.php (19)
in /var/www/html/Assignment_2/protected/controllers/UsersController.php (124)
in /var/www/html/Assignment_2/index.php (13)
2020/04/28 18:37:33 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/
---
2020/04/28 18:37:42 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/
---
2020/04/28 18:39:25 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/index
---
2020/04/28 19:08:28 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users
---
2020/04/28 19:36:59 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/create
---
2020/04/28 19:37:06 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in /var/www/yii/framework/web/CController.php:337
Stack trace:
#0 /var/www/yii/framework/web/CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 /var/www/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/view')
#10 /var/www/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /var/www/html/Assignment_2/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Assignment_2/index.php?r=users/view
HTTP_REFERER=http://localhost/Assignment_2/index.php?r=users/create
---
2020/04/29 10:05:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:09:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:10:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:10:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:48:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:48:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:50:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:50:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:50:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:50:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:50:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:51:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:51:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:52:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:52:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(2389): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php
---
2020/04/29 10:56:13 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[HY000]: General error: 6 Error on delete of 'C:\xampp\tmp\#sql2384_23_0.MYD' (Errcode: 13 - Permission denied). The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php (143)
in C:\xampp\htdocs\Assignment_2-master\index.php (13)
2020/04/29 10:56:13 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "Users" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2390
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\Assignment_2-master\protected\controllers\UsersController.php(143): CActiveRecord->__construct()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Assignment_2-master\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Assignment_2-master/index.php?r=users/index
HTTP_REFERER=http://localhost/Assignment_2-master/index.php?r=users/admin
---
